jobs:
  - deployment: Deploy
    displayName: Deploy
    environment: $(environment)
    pool: Default

    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureFunctionApp@1
            displayName: 'Azure functions app deploy'
            inputs:
              azureSubscription: $(azureSubscription)
              appType: functionAppLinux
              appName: ${{ parameters.funcAppName }}
              package: '$(Pipeline.Workspace)/drop/build$(Build.BuildId).zip'