# Python Function App to Linux on Azure
# Build a Python function app and deploy it to Azure as a Linux function app.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

pool: Default

variables:

  # Working Directory
  workingDirectory: '$(System.DefaultWorkingDirectory)/'

stages:

- stage: DeployDEV
  displayName: Deploy to dev environment
  variables:
  - group: webalerts-dev-vargroup

  jobs:
    - template: azure-pipelines-deploy-template.yml
      parameters:
        environment: development
        azureSub: rg-webnotifications_dev
        funcAppName: $(FunctionAppName)

