name: build-scraper
run-name: Build scraper container image
on: [push]
jobs:
  BuildTest:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r scraper/requirements.txt
      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 ./scraper --count --statistics --show-source
      - name: Run tests
        run: |
          pip install pytest
          pip install pytest-cov
          pytest --doctest-modules --junitxml=junit/test-results.xml --cov=. --cov-report=xml --cov-report=html
      - name: Test results
        uses: test-summary/action@v1.0
        with:
          paths: "junit/**/test-*.xml"
        if: always()
  CreateImage:
    name: Create scraper app image
    needs: BuildTest
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}  
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:scraper"
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/webalerts/scraper:latest